---
- name: Create Ansible Vault
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Encrypt the file with Ansible Vault
      shell: ansible-vault encrypt /root/secret.txt #replace with path and file name
      args:
        executable: /bin/bash  # Update this path to the correct location of bash
